### ISSUE TITLE
Support for background-image.

### ISSUE THREAD

**Issue by MeanEYE** [rstacruz/vim-hyperstyle#2]
Great plugin by the way, but I find myself looking for `background-image` shorthand. It's something I use quite often. If you could make something like `bgi` or similar to expand to this property, it would be great.

Thanks!

**Comment by rstacruz** [comment]
cool, wanna try doing a PR? :)

https://github.com/rstacruz/vim-hyperstyle/blob/master/python/definitions.py#L101-L105

**Comment by MeanEYE** [comment]
Oh, nice. Didn't know it was Python and well documented code at that. I'll take a look. It seems there's something for my use case. Reading this file I sad that `background` expands to include image, position and repeat. So that's really what I need.

Feel free to close this issue. Should I run into something I need I'll make a PR. :) Thanks!

**Comment by rstacruz** [comment]
unfortunately i _really did_ forget background-image in there man, sorry

**Comment by rstacruz** [comment]
There we go. You should be able to expand it from `bi` and `bgi` and `backi`

**Comment by rstacruz** [comment]
https://github.com/rstacruz/vim-hyperstyle/blob/master/REFERENCE.md#background-image

**Comment by MeanEYE** [comment]
Hah, thanks a lot.
